[package]
name = "boombox"
version = "0.0.0"
authors = ["Garrett Howard <garrett@mersh.com>"]
edition = "2021"

[dependencies]
adw = { package = "libadwaita", version = "0.1.1" }
gtk = { package = "gtk4", version = "0.4.8", features = ["v4_4"] }
